import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { encodePng } from '../scripts/verdigris-assets/png.mjs';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CLI = path.join('scripts', 'verdigris-assets', 'ingest.mjs');

function runCli(...args) {
  const result = spawnSync(process.execPath, [CLI, ...args], { cwd: REPO_ROOT, encoding: 'utf8' });
  return {
    status: result.status,
    stdout: (result.stdout || '').replaceAll('\r\n', '\n'),
    stderr: (result.stderr || '').replaceAll('\r\n', '\n'),
  };
}

function solidRgba(width, height, fill, painter) {
  const pixels = Buffer.alloc(width * height * 4);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * 4;
      let color = fill;
      if (painter) color = painter(x, y);
      pixels[i] = color[0];
      pixels[i + 1] = color[1];
      pixels[i + 2] = color[2];
      pixels[i + 3] = color[3];
    }
  }
  return encodePng(width, height, pixels);
}

function makeIntake(root) {
  fs.mkdirSync(path.join(root, 'panel-default.png.dir'), { recursive: true });
  const panel = solidRgba(24, 24, [90, 140, 80, 255], (x, y) =>
    x < 4 || y < 4 || x >= 20 || y >= 20 ? [40, 70, 35, 128] : [120 + ((x + y) % 60), 160, 90, 255]
  );
  const hover = solidRgba(24, 24, [150, 190, 110, 255], (x, y) =>
    x < 4 || y < 4 || x >= 20 || y >= 20 ? [70, 110, 50, 180] : [170 + ((x * 2 + y) % 50), 200, 120, 255]
  );
  fs.writeFileSync(path.join(root, 'panel-default.png'), panel);
  fs.writeFileSync(path.join(root, 'panel-hover.png'), hover);
  fs.writeFileSync(
    path.join(root, 'intake.json'),
    JSON.stringify({
      schemaVersion: 1,
      id: 'verdigris-test-pack',
      title: 'Deterministic Test Pack',
      provenance: 'synthetic fixtures generated by tests/asset-ingestion.test.mjs',
      derivatives: ['alpha', 'edge', 'height', 'depth', 'roughness-source'],
      components: [
        {
          id: 'panel',
          slice: [6, 6, 6, 6],
          contentInsets: [2, 2, 2, 2],
          edgeMode: 'stretch',
          states: {
            default: { file: 'panel-default.png', expectAlpha: true },
            hover: { file: 'panel-hover.png', expectAlpha: true },
          },
        },
      ],
    })
  );
}

const workRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'asset-intake-'));
const intakeDir = path.join(workRoot, 'intake');
makeIntake(intakeDir);

function outTree(label) {
  return path.join(workRoot, `out-${label}`);
}

{
  const label = 'valid intake ingests, emits manifest plus maps, and passes verify';
  const out = outTree('positive');
  const first = runCli('ingest', intakeDir, '--out', out, '--contact-sheet');
  assert.equal(first.status, 0, `expected pass:\n${first.stdout}\n${first.stderr}`);
  assert.match(first.stdout, /PASS ingest verdigris-test-pack \(1 components validated and promoted\)/);
  const packDir = path.join(out, 'assets', 'verdigris-ui', 'framepacks', 'verdigris-test-pack');
  const manifest = JSON.parse(fs.readFileSync(path.join(packDir, 'framepack.json'), 'utf8'));
  assert.equal(manifest.schemaVersion, 1);
  assert.equal(manifest.assetRoot, 'assets/verdigris-ui/framepacks/');
  assert.equal(manifest.components.length, 1);
  assert.equal(manifest.components[0].states.default.width, 24);
  assert.equal(manifest.components[0].states.default.hasAlpha, true);
  assert.equal(manifest.components[0].derivatives.length, 10);
  assert.ok(fs.existsSync(path.join(packDir, 'contact-sheet.png')), 'contact sheet must be emitted');
  assert.ok(!manifest.components[0].derivatives.some(d => d.role === 'normal-source'), 'must never emit normal-source');
  const verify = runCli('verify', packDir);
  assert.equal(verify.status, 0, `expected verify pass:\n${verify.stdout}\n${verify.stderr}`);
  console.log(`PASS ${label} (10 derivative maps + contact sheet)`);
}

{
  const label = 'identical input produces byte-identical output';
  const outA = outTree('det-a');
  const outB = outTree('det-b');
  runCli('ingest', intakeDir, '--out', outA, '--contact-sheet');
  runCli('ingest', intakeDir, '--out', outB, '--contact-sheet');
  function hashTree(root) {
    const hashes = [];
    for (const file of fs.readdirSync(root, { recursive: true })) {
      const full = path.join(root, file.toString());
      if (fs.statSync(full).isFile()) {
        hashes.push(`${file}=${Buffer.from(spawnSync('shasum', ['-a', '256', full]).stdout).toString().split(' ')[0]}`);
      }
    }
    return hashes.sort().join('\n');
  }
  assert.equal(hashTree(outA), hashTree(outB), 'output trees must be byte-identical');
  console.log(`PASS ${label}`);
}

{
  const label = 'slice bounds violating the frozen interface fail before promotion';
  const bad = path.join(workRoot, 'bad-slice');
  makeIntake(bad);
  const intake = JSON.parse(fs.readFileSync(path.join(bad, 'intake.json'), 'utf8'));
  intake.components[0].slice = [14, 14, 14, 14];
  fs.writeFileSync(path.join(bad, 'intake.json'), JSON.stringify(intake));
  const out = outTree('bad-slice-out');
  const result = runCli('ingest', bad, '--out', out);
  assert.equal(result.status, 1, `expected fail:\n${result.stdout}\n${result.stderr}`);
  assert.match(result.stderr, /slice left\+right \(14\+14\) must be less than source width 24/);
  assert.ok(!fs.existsSync(out), 'failed ingest must not create the output directory');
  console.log(`PASS ${label}`);
}

{
  const label = 'expectAlpha mismatch fails before promotion';
  const bad = path.join(workRoot, 'bad-alpha');
  makeIntake(bad);
  const opaque = solidRgba(24, 24, [10, 10, 10, 255]);
  fs.writeFileSync(path.join(bad, 'panel-hover.png'), opaque);
  const out = outTree('bad-alpha-out');
  const result = runCli('ingest', bad, '--out', out);
  assert.equal(result.status, 1, `expected fail:\n${result.stdout}\n${result.stderr}`);
  assert.match(result.stderr, /expectAlpha=true but panel-hover\.png is fully opaque/);
  assert.ok(!fs.existsSync(out));
  console.log(`PASS ${label}`);
}

{
  const label = 'invalid pack id fails schema validation before promotion';
  const bad = path.join(workRoot, 'bad-name');
  makeIntake(bad);
  const intake = JSON.parse(fs.readFileSync(path.join(bad, 'intake.json'), 'utf8'));
  intake.id = 'Verdigris Test Pack';
  fs.writeFileSync(path.join(bad, 'intake.json'), JSON.stringify(intake));
  const out = outTree('bad-name-out');
  const result = runCli('ingest', bad, '--out', out);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /fails pattern/);
  assert.ok(!fs.existsSync(out));
  console.log(`PASS ${label}`);
}

{
  const label = 'normal-source is refused instead of pretending to synthesize normal maps';
  const bad = path.join(workRoot, 'bad-normal');
  makeIntake(bad);
  const intake = JSON.parse(fs.readFileSync(path.join(bad, 'intake.json'), 'utf8'));
  intake.derivatives.push('normal-source');
  fs.writeFileSync(path.join(bad, 'intake.json'), JSON.stringify(intake));
  const out = outTree('bad-normal-out');
  const result = runCli('ingest', bad, '--out', out);
  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /"normal-source" is not an allowed value/,
    'intake schema must refuse normal-source so the tool never fakes a normal map'
  );
  assert.ok(!fs.existsSync(out));
  console.log(`PASS ${label}`);
}

{
  const label = 'verify mode detects a tampered asset checksum';
  const out = outTree('tamper');
  runCli('ingest', intakeDir, '--out', out);
  const packDir = path.join(out, 'assets', 'verdigris-ui', 'framepacks', 'verdigris-test-pack');
  fs.writeFileSync(path.join(packDir, 'panel-default.png'), Buffer.from('tampered'));
  const result = runCli('verify', packDir);
  assert.equal(result.status, 1, `expected verify fail:\n${result.stdout}\n${result.stderr}`);
  assert.match(result.stderr, /checksum mismatch for panel-default\.png/);
  console.log(`PASS ${label}`);
}

{
  const label = 'deterministic contact sheet matches the committed expected artifact';
  const sheetSource = path.join(workRoot, 'out-positive', 'assets', 'verdigris-ui', 'framepacks', 'verdigris-test-pack', 'contact-sheet.png');
  const committed = path.join(REPO_ROOT, 'tests', 'fixtures', 'assets', 'expected-contact-sheet.png');
  assert.ok(fs.existsSync(sheetSource), 'sheet must exist');
  if (process.env.UPDATE_SHEET === '1') {
    fs.copyFileSync(sheetSource, committed);
    console.log(`UPDATE ${label} (regenerated committed artifact; rerun test to confirm)`);
  } else {
    const generated = fs.readFileSync(sheetSource);
    const expected = fs.readFileSync(committed);
    assert.ok(generated.equals(expected), 'generated contact sheet must be byte-identical to the committed artifact');
    console.log(`PASS ${label}`);
  }
}

fs.rmSync(workRoot, { recursive: true, force: true });
console.log('PASS asset-ingestion.test.mjs');
process.exit(0);
