import assert from 'node:assert/strict';
import { execFileSync, spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const checker = join(repoRoot, 'scripts/deploy-smoke.mjs');
const fixtureRepo = mkdtempSync(join(tmpdir(), 'wizard-deploy-smoke-'));
const fixturePort = 8172;
const requests = [];
let mode = 'transient';
let transientServed = false;

function git(...args) {
  return execFileSync('git', args, { cwd: fixtureRepo, encoding: 'utf8' }).trim();
}

function write(path, content) {
  const destination = join(fixtureRepo, path);
  mkdirSync(dirname(destination), { recursive: true });
  writeFileSync(destination, content);
}

function runCli(args) {
  return new Promise((resolvePromise) => {
    const child = spawn(process.execPath, [checker, ...args], { cwd: fixtureRepo });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk) => { stdout += chunk; });
    child.stderr.on('data', (chunk) => { stderr += chunk; });
    child.on('close', (status) => resolvePromise({ status, stdout, stderr }));
  });
}

const server = createServer((request, response) => {
  const url = new URL(request.url, `http://127.0.0.1:${fixturePort}/`);
  requests.push({ path: url.pathname, at: Date.now(), mode });

  if (mode === 'transient' && url.pathname === '/modules.json' && !transientServed) {
    transientServed = true;
    response.writeHead(503, { 'content-type': 'text/plain' });
    response.end('not propagated yet');
    return;
  }

  const relative = url.pathname === '/' ? 'index.html' : decodeURIComponent(url.pathname.slice(1));
  let body;
  try {
    body = readFileSync(join(fixtureRepo, relative));
  } catch {
    response.writeHead(404, { 'content-type': 'text/plain' });
    response.end('missing fixture');
    return;
  }
  if (mode === 'stale' && relative === 'tools/alpha/index.html') {
    body = Buffer.from('<h1>stale alpha deployment</h1>\n');
  }

  const contentType = relative.endsWith('.json')
    ? 'application/json'
    : relative.endsWith('.js')
      ? 'application/javascript'
      : relative.endsWith('.css')
        ? 'text/css'
        : relative.endsWith('.html')
          ? 'text/html'
          : 'application/octet-stream';
  response.writeHead(200, {
    'content-type': contentType,
    etag: '"fixture-etag"',
    'last-modified': 'Fri, 21 Aug 2026 00:00:00 GMT',
  });
  response.end(body);
});

try {
  git('init', '--initial-branch=gh-pages');
  git('config', 'user.name', 'WIZARD fixture');
  git('config', 'user.email', 'fixture@example.invalid');
  write('index.html', '<title>WIZARD</title><h1>WIZARD</h1><p>Verdigris Systems Laboratory</p><script src="shared/runtime.js?v=7"></script>\n');
  write('modules.json', JSON.stringify({
    generatedBy: 'scripts/wizard-lab.mjs',
    schemaVersion: 1,
    doNotEdit: true,
    modules: [
      { id: 'wizard.alpha', visibility: 'dashboard', launch: 'tools/alpha/index.html' },
      { id: 'wizard.beta', visibility: 'dashboard', launch: 'tools/beta/index.html' },
      { id: 'wizard.archive', visibility: 'archive', launch: 'tools/archive/index.html' },
    ],
  }, null, 2));
  write('modules.generated.js', '/* generated by scripts/wizard-lab.mjs; do not edit */\nwindow.WIZARD_REGISTRY = {};\n');
  write('tools/alpha/index.html', '<h1>alpha</h1><link href="theme.css?v=2" rel="stylesheet">\n');
  write('tools/alpha/theme.css', 'body { color: green; }\n');
  write('tools/beta/index.html', '<h1>beta</h1>\n');
  write('tools/archive/index.html', '<h1>archive must not be requested</h1>\n');
  write('shared/runtime.js', 'fetch("data.bin?v=3");\n');
  write('shared/data.bin', 'fixture-data\n');
  git('add', '.');
  git('commit', '-m', 'fixture deployment');
  const expectedSha = git('rev-parse', 'HEAD');

  await new Promise((resolvePromise, reject) => {
    server.once('error', reject);
    server.listen(fixturePort, '127.0.0.1', resolvePromise);
  });
  const baseArgs = [
    '--base-url', `http://127.0.0.1:${fixturePort}/`,
    '--expected-sha', expectedSha,
    '--attempts', '3',
    '--backoff-ms', '25',
    '--timeout-ms', '1000',
  ];

  const success = await runCli(baseArgs);
  console.log(`fixture fresh-after-backoff (exit ${success.status})`);
  console.log(success.stdout.trim());
  if (success.stderr.trim()) console.log(success.stderr.trim());
  assert.equal(success.status, 0);
  assert.match(success.stdout, new RegExp(`expected_sha=${expectedSha} local_head=${expectedSha}`));
  assert.match(success.stdout, /header_resolution .*etag="fixture-etag" .*last_modified=Fri, 21 Aug 2026 00:00:00 GMT/);
  assert.match(success.stdout, /identity: WIZARD — Verdigris Systems Laboratory/);
  assert.match(success.stdout, /generated_registry modules=3 active_launches=2/);
  assert.match(success.stdout, /RETRY attempt=1\/3 delay_ms=25 .*HTTP 503/);
  assert.match(success.stdout, /checked_resources total=8 active_launches=2 shared_assets=1 cache_pinned_assets=3/);
  assert.match(success.stdout, new RegExp(`PASS deploy-smoke expected_sha=${expectedSha} resources=8`));
  assert.equal(requests.filter((entry) => entry.path === '/tools/alpha/index.html').length, 1);
  assert.equal(requests.filter((entry) => entry.path === '/tools/beta/index.html').length, 1);
  assert.equal(requests.filter((entry) => entry.path === '/tools/archive/index.html').length, 0);
  assert.equal(requests.filter((entry) => entry.path === '/shared/runtime.js').length, 1);
  assert.equal(requests.filter((entry) => entry.path === '/shared/data.bin').length, 1);
  const modulesRequests = requests.filter((entry) => entry.path === '/modules.json');
  assert.equal(modulesRequests.length, 2);
  assert.ok(modulesRequests[1].at - modulesRequests[0].at >= 20, 'retry must perform a real backoff');

  mode = 'stale';
  requests.length = 0;
  const staleStarted = Date.now();
  const stale = await runCli(baseArgs);
  const staleElapsed = Date.now() - staleStarted;
  console.log(`fixture forced-stale-content (exit ${stale.status})`);
  console.log(stale.stdout.trim());
  console.log(stale.stderr.trim());
  assert.equal(stale.status, 1);
  assert.match(stale.stderr, new RegExp(`FAIL deploy-smoke url=http://127\\.0\\.0\\.1:${fixturePort}/tools/alpha/index\\.html`));
  assert.match(stale.stderr, new RegExp(`expected_sha=${expectedSha}`));
  assert.match(stale.stderr, /attempts=3 reason=content mismatch expected_digest=[0-9a-f]{64} actual_digest=[0-9a-f]{64}/);
  assert.equal(requests.filter((entry) => entry.path === '/tools/alpha/index.html').length, 3);
  assert.ok(staleElapsed >= 65, 'stale failure must honor 25ms and 50ms backoff delays');

  const ceiling = await runCli([...baseArgs, '--attempts', '6']);
  assert.equal(ceiling.status, 2);
  assert.match(ceiling.stderr, /attempts must be an integer from 1 through 5/);

  const workflow = readFileSync(join(repoRoot, '.github/workflows/deploy-smoke.yml'), 'utf8');
  assert.match(workflow, /^on:\n  workflow_run:\n    workflows: \[pages-build-deployment\]\n    types: \[completed\]\n    branches: \[gh-pages\]$/m);
  assert.doesNotMatch(workflow, /pull_request_target|^\s+push:|^\s+workflow_dispatch:/m);
  assert.match(workflow, /^permissions:\n  contents: read$/m);
  assert.doesNotMatch(workflow, /^\s+[a-z-]+: write$/m);
  assert.match(workflow, /github\.event\.workflow_run\.conclusion == 'success'/);
  assert.match(workflow, /github\.event\.workflow_run\.head_branch == 'gh-pages'/);
  assert.match(workflow, /ref: \$\{\{ github\.event\.workflow_run\.head_sha \}\}/);
  assert.match(workflow, /DEPLOYED_SHA: \$\{\{ github\.event\.workflow_run\.head_sha \}\}/);
  assert.match(workflow, /DEPLOY_BASE_URL: https:\/\/alexkorol\.github\.io\/WIZARD\//);
  assert.match(workflow, /persist-credentials: false/);
  assert.match(workflow, /group: deploy-smoke-production\n  cancel-in-progress: true/);
  assert.match(workflow, /timeout-minutes: 5/);
  assert.doesNotMatch(workflow, /secrets\.|notify|rollback|gh api|git push/);

  console.log('ok deploy smoke: exact SHA/content, headers, identity, registry, every active launch, shared and pinned assets, bounded backoff, stale failure, read-only completion trigger');
} finally {
  await new Promise((resolvePromise) => server.close(resolvePromise));
  rmSync(fixtureRepo, { recursive: true, force: true });
}
