import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.min.js";

const TAU=Math.PI*2;
const canvas=document.querySelector("#world");
const fpsEl=document.querySelector("#fps");
const qualityButton=document.querySelector("#quality");
const soundButton=document.querySelector("#sound");
let quality="high",muted=true;

function seeded(seed){let value=seed>>>0;return()=>{value=(value*1664525+1013904223)>>>0;return value/4294967296}}
function shape(rx,rz,seed){const random=seeded(seed),s=new THREE.Shape(),count=72;for(let i=0;i<=count;i++){const a=i/count*TAU,n=1+Math.sin(a*3+seed)*.1+Math.sin(a*7-seed)*.045+(random()-.5)*.07,x=Math.cos(a)*rx*n,y=Math.sin(a)*rz*n;i?s.lineTo(x,y):s.moveTo(x,y)}return s}
function land(group,x,z,rx,rz,color,seed){const g=new THREE.ExtrudeGeometry(shape(rx,rz,seed),{depth:.14,bevelEnabled:true,bevelSize:.06,bevelThickness:.04,bevelSegments:2});g.rotateX(-Math.PI/2);g.translate(x,.64,z);const mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:.88}));mesh.castShadow=mesh.receiveShadow=true;group.add(mesh);return{x,z,rx,rz,seed}}

function boot(){
  let renderer;
  try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:"high-performance"})}catch(error){document.querySelector("#fallback").hidden=false;return}
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x01030a);scene.fog=new THREE.FogExp2(0x020711,.012);
  const camera=new THREE.PerspectiveCamera(43,1,.1,80);camera.position.set(8.8,8.4,11.8);
  renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.22;
  const world=new THREE.Group();world.rotation.y=-.24;scene.add(world);
  const oceanMaterial=new THREE.MeshPhysicalMaterial({color:0x087c9c,roughness:.18,metalness:.08,clearcoat:.65,clearcoatRoughness:.16});
  const ocean=new THREE.Mesh(new THREE.CylinderGeometry(6.25,6.25,.42,128),oceanMaterial);ocean.scale.z=.74;ocean.receiveShadow=true;world.add(ocean);
  const crust=new THREE.Mesh(new THREE.ConeGeometry(6.18,4.2,96,7),new THREE.MeshStandardMaterial({color:0x17141a,roughness:.98,flatShading:true}));crust.position.y=-2.25;crust.scale.z=.74;crust.castShadow=true;world.add(crust);
  const lands=[land(world,-2,-.15,2.45,1.55,0x657f31,4),land(world,1.65,.25,2.05,1.45,0xa06a2c,8),land(world,-.2,1.85,2.1,.8,0x557331,11),land(world,-.3,-2,2,.75,0x7c8c32,15),land(world,3.7,-1.4,.72,.45,0x8a6b2b,23),land(world,-4.35,1.35,.65,.42,0x52752f,31)];
  const random=seeded(91),matrix=new THREE.Matrix4(),q=new THREE.Quaternion(),scale=new THREE.Vector3();
  const mountains=new THREE.InstancedMesh(new THREE.ConeGeometry(.18,.9,7,3),new THREE.MeshStandardMaterial({color:0x55483f,roughness:.95,flatShading:true}),150);mountains.castShadow=true;let mc=0;
  lands.slice(0,4).forEach((l,li)=>{const count=li===1?38:27;for(let i=0;i<count;i++){const t=i/count,px=l.x+(t-.5)*l.rx*1.45+(random()-.5)*.24,pz=l.z+Math.sin(t*Math.PI*2+l.seed)*l.rz*.22+(random()-.5)*.2,h=.45+random()*.82;scale.set(.65+random()*.8,h,.65+random()*.75);matrix.compose(new THREE.Vector3(px,.83+h*.43,pz),q,scale);mountains.setMatrixAt(mc++,matrix)}});mountains.count=mc;world.add(mountains);
  const trees=new THREE.InstancedMesh(new THREE.ConeGeometry(.045,.22,5),new THREE.MeshStandardMaterial({color:0x163f24,roughness:1}),900);trees.castShadow=true;let tc=0;lands.slice(0,4).forEach(l=>{for(let i=0;i<210;i++){const a=random()*TAU,r=Math.sqrt(random())*.78,s=.65+random()*.9;matrix.compose(new THREE.Vector3(l.x+Math.cos(a)*l.rx*r,.9,l.z+Math.sin(a)*l.rz*r),q,new THREE.Vector3(s,s,s));trees.setMatrixAt(tc++,matrix)}});trees.count=tc;world.add(trees);
  const temples=new THREE.InstancedMesh(new THREE.CylinderGeometry(.075,.1,.18,8),new THREE.MeshStandardMaterial({color:0xc48b38,metalness:.5,roughness:.38,emissive:0x2b1002}),42);for(let i=0;i<42;i++){const l=lands[i%4],a=random()*TAU,r=random()*.62,s=i%13===0?2.1:.8+random()*.7;matrix.compose(new THREE.Vector3(l.x+Math.cos(a)*l.rx*r,.93,l.z+Math.sin(a)*l.rz*r),q,new THREE.Vector3(s,s,s));temples.setMatrixAt(i,matrix)}world.add(temples);
  const rimMaterial=new THREE.ShaderMaterial({transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,uniforms:{uTime:{value:0}},vertexShader:`varying vec3 n,p;void main(){n=normalize(normalMatrix*normal);p=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform float uTime;varying vec3 n,p;void main(){float pulse=.72+.2*sin(uTime*.35+p.x*2.3+p.z*1.7);float edge=pow(1.-abs(dot(normalize(n),vec3(0.,1.,0.))),1.8);gl_FragColor=vec4(.22,.74,1.,edge*pulse*.42);}`});
  const rim=new THREE.Mesh(new THREE.TorusGeometry(6.22,.16,12,180),rimMaterial);rim.rotation.x=Math.PI/2;rim.scale.y=.74;rim.position.y=.24;world.add(rim);
  const fogCount=1800,fogPositions=new Float32Array(fogCount*3),fogSizes=new Float32Array(fogCount);for(let i=0;i<fogCount;i++){const a=random()*TAU,r=5.7+random()*.75;fogPositions[i*3]=Math.cos(a)*r;fogPositions[i*3+1]=.45+(random()-.5)*.34;fogPositions[i*3+2]=Math.sin(a)*r*.74;fogSizes[i]=10+random()*28}const fogGeometry=new THREE.BufferGeometry();fogGeometry.setAttribute("position",new THREE.BufferAttribute(fogPositions,3));fogGeometry.setAttribute("aSize",new THREE.BufferAttribute(fogSizes,1));const fogMaterial=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0}},vertexShader:`uniform float uTime;attribute float aSize;varying float a;void main(){vec3 p=position;p.y+=sin(uTime*.12+position.x*1.7)*.06;vec4 mv=modelViewMatrix*vec4(p,1.);gl_PointSize=aSize*(150./-mv.z);a=.08+.08*sin(position.z*3.+uTime*.18);gl_Position=projectionMatrix*mv;}`,fragmentShader:`varying float a;void main(){float d=length(gl_PointCoord-.5);gl_FragColor=vec4(.55,.78,.94,smoothstep(.5,.05,d)*a);}`});world.add(new THREE.Points(fogGeometry,fogMaterial));
  const falls=[.1,.82,2.1,3.15,4.28,5.4],fallMaterial=new THREE.ShaderMaterial({transparent:true,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0}},vertexShader:`uniform float uTime;varying vec2 v;void main(){v=uv;vec3 p=position;p.x+=sin(uv.y*15.-uTime*2.)*.018*uv.y;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`uniform float uTime;varying vec2 v;void main(){float c=smoothstep(.5,.05,abs(v.x-.5)),flow=.65+.35*sin(v.y*42.-uTime*5.),fade=smoothstep(1.,.72,v.y)*smoothstep(0.,.08,v.y);gl_FragColor=vec4(.18,.7,1.,c*flow*fade*.8);}`});falls.forEach(a=>{const mesh=new THREE.Mesh(new THREE.PlaneGeometry(.14,3.6,3,64),fallMaterial);mesh.position.set(Math.cos(a)*6.08,-1.5,Math.sin(a)*6.08*.74);mesh.rotation.y=-a;world.add(mesh)});
  const dc=420,dp=new Float32Array(dc*3),dd=new Float32Array(dc*2);for(let i=0;i<dc;i++){const a=falls[i%falls.length]+(random()-.5)*.018;dp[i*3]=Math.cos(a)*6.08;dp[i*3+2]=Math.sin(a)*6.08*.74;dd[i*2]=random();dd[i*2+1]=.7+random()*.8}const dg=new THREE.BufferGeometry();dg.setAttribute("position",new THREE.BufferAttribute(dp,3));dg.setAttribute("aData",new THREE.BufferAttribute(dd,2));const dm=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0}},vertexShader:`uniform float uTime;attribute vec2 aData;varying float a;void main(){vec3 p=position;float f=mod(uTime*aData.y+aData.x*4.,4.2);p.y=.15-f;p.xz*=1.+f*.018;vec4 mv=modelViewMatrix*vec4(p,1.);gl_PointSize=(2.2+aData.x*2.)*(120./-mv.z);a=1.-f/4.2;gl_Position=projectionMatrix*mv;}`,fragmentShader:`varying float a;void main(){float d=length(gl_PointCoord-.5);gl_FragColor=vec4(.25,.75,1.,smoothstep(.5,.1,d)*a);}`});world.add(new THREE.Points(dg,dm));
  const sg=new THREE.BufferGeometry(),sp=new Float32Array(2700*3),sr=seeded(12);for(let i=0;i<2700;i++){const r=18+sr()*35,t=sr()*TAU,p=Math.acos(2*sr()-1);sp[i*3]=r*Math.sin(p)*Math.cos(t);sp[i*3+1]=r*Math.cos(p);sp[i*3+2]=r*Math.sin(p)*Math.sin(t)}sg.setAttribute("position",new THREE.BufferAttribute(sp,3));scene.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0xcfe7ff,size:.035})));
  scene.add(new THREE.HemisphereLight(0x8bc8ff,0x130b08,1.4));const sun=new THREE.DirectionalLight(0xffd19a,5.3);sun.position.set(-8,11,4);scene.add(sun);const abyss=new THREE.PointLight(0x087dff,36,18,1.8);abyss.position.set(0,-5.2,1);scene.add(abyss);
  let started=performance.now(),lastFps=started,frames=0,dragging=false,dragStart=0,dragOrigin=0,dragOffset=0,raf;
  function applyQuality(){renderer.setPixelRatio(Math.min(devicePixelRatio,quality==="high"?1.65:1.05));renderer.shadowMap.enabled=quality==="high";sun.castShadow=quality==="high";sun.shadow.mapSize.set(quality==="high"?2048:1024,quality==="high"?2048:1024);resize()}
  function resize(){renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);camera.aspect=canvas.clientWidth/canvas.clientHeight;camera.updateProjectionMatrix()}
  function animate(now){const time=(now-started)/1000;world.rotation.y=-.24+Math.sin(time*.085)*.055+dragOffset;oceanMaterial.roughness=.16+Math.sin(time*.34)*.025;rimMaterial.uniforms.uTime.value=fogMaterial.uniforms.uTime.value=fallMaterial.uniforms.uTime.value=dm.uniforms.uTime.value=time;camera.position.y=8.4+Math.sin(time*.12)*.16;camera.lookAt(0,-.55,0);renderer.render(scene,camera);frames++;if(now-lastFps>800){fpsEl.textContent=Math.round(frames*1000/(now-lastFps))+" FPS";frames=0;lastFps=now}raf=requestAnimationFrame(animate)}
  canvas.addEventListener("pointerdown",e=>{dragging=true;dragStart=e.clientX;dragOrigin=dragOffset;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(dragging)dragOffset=dragOrigin+(e.clientX-dragStart)*.0035});canvas.addEventListener("pointerup",e=>{dragging=false;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId)});addEventListener("resize",resize);applyQuality();raf=requestAnimationFrame(animate);
  qualityButton.addEventListener("click",()=>{quality=quality==="high"?"balanced":"high";qualityButton.textContent=quality.toUpperCase();applyQuality()});soundButton.addEventListener("click",()=>{muted=!muted;soundButton.textContent=muted?"SOUND OFF":"SOUND ON"});
}
boot();
