const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const playwright = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/Alex/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const url = process.env.DEMO_URL || 'http://127.0.0.1:8789/art_studies/starter-derivatives-v01/demo/';

(async () => {
  const browser = await playwright.chromium.launch({channel:'msedge', headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}, deviceScaleFactor:1});
  const errors = [], badResponses = [], requests = [];
  page.on('request', r => requests.push(r.url()));
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.status() >= 400) badResponses.push([r.status(), r.url()]); });
  await page.goto(url);
  await page.waitForFunction(() => window.demoDebug?.getState().ready);
  const state = () => page.evaluate(() => window.demoDebug.getState());
  assert.equal((await state()).study, 'motion');
  assert.equal((await state()).gait, 'sprint');
  assert(Math.abs(Number(await page.inputValue('#fps'))-120*8/88)<.01,'Use recorded run timing');
  const initialFrame=(await state()).frame;
  await page.waitForFunction(f=>window.demoDebug.getState().frame!==f,initialFrame);
  await page.getByRole('button',{name:'Play walk',exact:false}).click();
  assert.equal((await state()).study,'motion'); assert.equal((await state()).gait,'walk'); assert.equal((await state()).paused,false);
  assert(Math.abs(Number(await page.inputValue('#fps'))-120*8/130)<.01,'Use recorded walk timing');
  await page.click('#next');
  await page.getByRole('button',{name:'Play sprint',exact:false}).click();
  assert.equal((await state()).paused,false); assert.equal((await state()).gait,'sprint');
  const count = await page.evaluate(() => Object.values(window.demoDebug.getManifest().clips).reduce((n,c) => n+c.frames.length,0));
  assert.equal(count, 128);
  assert.equal((await state()).processing,'blender');
  const calibration=await page.evaluate(()=>{
    const c=window.demoDebug.getCalibration();
    return {ppu:c.player_plane_px_per_m,samples:c.ground_samples.map(s=>({expected:s.pixel,actual:window.demoDebug.project(...s.world)})),plane:window.demoDebug.project(0,0),far:window.demoDebug.project(0,4)};
  });
  assert(Math.abs(calibration.ppu-48)<.001);
  assert.equal(calibration.plane[2],1);
  assert(calibration.far[2]<1,'Keep perspective in the distance');
  for(const s of calibration.samples)for(let i=0;i<2;i++)assert(Math.abs(s.expected[i]-s.actual[i])<.001,'JS projection must match Blender');
  await page.screenshot({path:path.join(__dirname,'review/demo-village.png')});
  await page.selectOption('#zoom','1');
  await page.screenshot({path:path.join(__dirname,'review/demo-parity-native.png')});
  await page.selectOption('#zoom','2');
  assert(!requests.some(url=>url.includes('/demo/assets/')),'Retired mixed-density scenery must not load');
  await page.locator('#scene').focus();
  const x = (await state()).x;
  await page.keyboard.down('KeyD');
  await page.waitForFunction(before => window.demoDebug.getState().x > before+5, x);
  await page.keyboard.up('KeyD');
  assert.equal((await state()).dir, 'right');
  await page.selectOption('#study','motion');
  await page.locator('#scene').focus();
  await page.keyboard.down('Shift'); await page.keyboard.down('KeyW');
  await page.waitForFunction(() => window.demoDebug.getState().gait === 'sprint' && window.demoDebug.getState().dir === 'back');
  await page.keyboard.up('KeyW'); await page.keyboard.up('Shift');
  assert.equal((await state()).dir, 'back');
  await page.click('[data-sex="female"]');
  await page.click('[data-gait="walk"]');
  await page.click('[data-dir="right"]');
  await page.click('#next');
  const paused = await state();
  assert.equal(paused.paused,true); assert.equal(paused.frameCount,8);
  await page.evaluate(() => new Promise(resolve => setTimeout(resolve,400)));
  assert.equal((await state()).frame,paused.frame);
  await page.click('#next'); assert.equal((await state()).frame,(paused.frame+1)%8);
  await page.selectOption('#ground','light');
  await page.selectOption('#zoom','1');
  await page.screenshot({path:path.join(__dirname,'review/demo-motion-native.png')});
  assert.equal(await page.locator('#study option').count(),1);
  assert.equal(await page.locator('#processing option').count(),1);
  assert(!requests.some(url=>/web-v01|web-padding|frames-tuned|native-alpha|manifest-tuned/.test(url)),'Retired generated assets must not load');
  await page.setViewportSize({width:800,height:800});
  await page.screenshot({path:path.join(__dirname,'review/demo-compact.png')});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth),false);
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(new URL('pipeline.html',url).href);
  await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('0 generated sheets'));
  assert.equal(await page.locator('#clip option').count(),16);
  await page.selectOption('#clip','male-walk-left');
  await page.click('#next');
  assert((await page.locator('#frameTitle').innerText()).includes('2/8'));
  assert((await page.locator('#frameLink').getAttribute('href')).endsWith('male-walk-left-2.png'));
  assert.deepEqual(errors,[]); assert.deepEqual(badResponses,[]);
  const result={passed:true,frameCount:count,checks:['128 Blender frames','camera projection','recorded motion timing','walk and sprint controls','keyboard movement','8-frame pause and step','reference-only loading','retired pipeline redirects to clean review','16 reference cycles','compact layout'],pageErrors:errors,badResponses};
  fs.writeFileSync(path.join(__dirname,'review/demo-verification.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result)); await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
