const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const playwright = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/Alex/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const url = process.env.DEMO_URL || 'http://127.0.0.1:8789/art_studies/starter-derivatives-v01/demo/';

(async () => {
  const browser = await playwright.chromium.launch({channel:'msedge', headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}, deviceScaleFactor:1});
  const errors = [], badResponses = [], requests = [];
  page.on('request', r => requests.push(r.url()));
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.status() >= 400) badResponses.push([r.status(), r.url()]); });
  await page.goto(url);
  await page.waitForFunction(() => window.demoDebug?.getState().ready);
  const state = () => page.evaluate(() => window.demoDebug.getState());
  assert.equal((await state()).study, 'motion');
  assert.equal((await state()).gait, 'sprint');
  assert(Math.abs(Number(await page.inputValue('#fps'))-120*8/88)<.01,'Use recorded run timing');
  const initialFrame=(await state()).frame;
  await page.waitForFunction(f=>window.demoDebug.getState().frame!==f,initialFrame);
  await page.selectOption('#study','club');
  await page.getByRole('button',{name:'Play walk',exact:false}).click();
  assert.equal((await state()).study,'motion'); assert.equal((await state()).gait,'walk'); assert.equal((await state()).paused,false);
  assert(Math.abs(Number(await page.inputValue('#fps'))-120*8/130)<.01,'Use recorded walk timing');
  await page.click('#next');
  await page.getByRole('button',{name:'Play sprint',exact:false}).click();
  assert.equal((await state()).paused,false); assert.equal((await state()).gait,'sprint');
  const count = await page.evaluate(() => Object.values(window.demoDebug.getManifest().clips).reduce((n,c) => n+c.frames.length,0));
  assert.equal(count, 128);
  assert.equal((await state()).processing,'blender');
  const calibration=await page.evaluate(()=>{
    const c=window.demoDebug.getCalibration();
    return {ppu:c.player_plane_px_per_m,samples:c.ground_samples.map(s=>({expected:s.pixel,actual:window.demoDebug.project(...s.world)})),plane:window.demoDebug.project(0,0),far:window.demoDebug.project(0,4)};
  });
  assert(Math.abs(calibration.ppu-48)<.001);
  assert.equal(calibration.plane[2],1);
  assert(calibration.far[2]<1,'Keep perspective in the distance');
  for(const s of calibration.samples)for(let i=0;i<2;i++)assert(Math.abs(s.expected[i]-s.actual[i])<.001,'JS projection must match Blender');
  await page.screenshot({path:path.join(__dirname,'review/demo-village.png')});
  await page.selectOption('#zoom','1');
  await page.screenshot({path:path.join(__dirname,'review/demo-parity-native.png')});
  await page.selectOption('#zoom','2');
  assert(!requests.some(url=>url.includes('/demo/assets/')),'Retired mixed-density scenery must not load');
  await page.selectOption('#processing','tuned');
  await page.locator('#scene').focus();
  const x = (await state()).x;
  await page.keyboard.down('KeyD');
  await page.waitForFunction(before => window.demoDebug.getState().x > before+5, x);
  await page.keyboard.up('KeyD');
  assert.equal((await state()).dir, 'right');
  await page.selectOption('#study','motion');
  await page.locator('#scene').focus();
  await page.keyboard.down('Shift'); await page.keyboard.down('KeyW');
  await page.waitForFunction(() => window.demoDebug.getState().gait === 'sprint' && window.demoDebug.getState().dir === 'back');
  await page.keyboard.up('KeyW'); await page.keyboard.up('Shift');
  assert.equal((await state()).dir, 'back');
  await page.click('[data-sex="female"]');
  await page.click('[data-gait="walk"]');
  await page.click('[data-dir="right"]');
  await page.click('#next');
  const paused = await state();
  assert.equal(paused.paused,true); assert.equal(paused.frameCount,4);
  await page.evaluate(() => new Promise(resolve => setTimeout(resolve,400)));
  assert.equal((await state()).frame,paused.frame);
  await page.click('#next'); assert.equal((await state()).frame,(paused.frame+1)%4);
  await page.selectOption('#ground','light');
  await page.selectOption('#zoom','1');
  await page.screenshot({path:path.join(__dirname,'review/demo-motion-native.png')});
  await page.selectOption('#study','darts');
  await page.click('[data-dir="right"]');
  assert.equal((await state()).frameCount,0);
  await page.waitForFunction(() => document.querySelector('#notice').textContent.includes('No generated frame'));
  await page.click('[data-dir="front"]');
  assert.equal((await state()).frameCount,1);
  await page.selectOption('#ground','dark');
  await page.selectOption('#zoom','2');
  await page.screenshot({path:path.join(__dirname,'review/demo-equipment.png')});
  await page.selectOption('#study','diagonals');
  for (const dir of ['se','ne','nw','sw']) {
    await page.click(`[data-dir="${dir}"]`);
    assert((await state()).frameSource.includes(`diagonals-${dir}`));
  }
  await page.selectOption('#study','focused-walk');
  await page.click('[data-dir="right"]');
  assert.equal((await state()).frameCount,4);
  assert.equal(await page.evaluate(() => document.querySelector('#scene').getContext('2d').imageSmoothingEnabled),false);
  await page.selectOption('#processing','before'); assert.equal((await state()).processing,'before');
  await page.selectOption('#processing','tuned'); assert((await state()).frameSource.includes('frames-tuned/'));
  await page.setViewportSize({width:800,height:800});
  await page.screenshot({path:path.join(__dirname,'review/demo-compact.png')});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth),false);
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(new URL('pipeline.html',url).href);
  await page.waitForFunction(()=>document.querySelector('#metrics').textContent.includes('Detected grid'));
  await page.selectOption('#sheet','male-sprint');
  await page.selectOption('#row','2');
  await page.waitForFunction(()=>document.body.dataset.rendered==='male-sprint/2/1');
  await page.screenshot({path:path.join(__dirname,'review/demo-pixel-transfer.png')});
  assert.deepEqual(errors,[]); assert.deepEqual(badResponses,[]);
  const result = {passed:true,frameCount:count,checks:['Blender ground projection agrees with browser','unit scale at player plane and perspective depth scaling','retired mixed-density scenery does not load','native and integer-enlarged scene inspected','sprint animates on initial load','Play walk switches out of idle','Play sprint resumes from paused frame','before/tuned comparison switches assets','source-transfer inspector loads','all sprite assets decode','keyboard movement','shift sprint selection','explicit facing mapping','sex change','pause and frame stepping','missing combinations remain empty','all four diagonal references','focused walk strip','nearest-neighbor canvas','compact layout'],pageErrors:errors,badResponses};
  fs.writeFileSync(path.join(__dirname,'review/demo-verification.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result)); await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
