const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const playwright = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/Alex/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const url = process.env.DEMO_URL || 'http://127.0.0.1:8789/art_studies/starter-derivatives-v01/demo/';

(async () => {
  const browser = await playwright.chromium.launch({channel:'msedge', headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}, deviceScaleFactor:1});
  const errors = [], badResponses = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.status() >= 400) badResponses.push([r.status(), r.url()]); });
  await page.goto(url);
  await page.waitForFunction(() => window.demoDebug?.getState().ready);
  const state = () => page.evaluate(() => window.demoDebug.getState());
  assert.equal((await state()).study, 'unarmed');
  const count = await page.evaluate(() => Object.values(window.demoDebug.getManifest().clips).reduce((n,c) => n+c.frames.length,0));
  assert.equal(count, 96);
  await page.screenshot({path:path.join(__dirname,'review/demo-village.png')});
  await page.locator('#scene').focus();
  const x = (await state()).x;
  await page.keyboard.down('KeyD');
  await page.waitForFunction(before => window.demoDebug.getState().x > before+5, x);
  await page.keyboard.up('KeyD');
  assert.equal((await state()).dir, 'right');
  await page.selectOption('#study','motion');
  await page.locator('#scene').focus();
  await page.keyboard.down('Shift'); await page.keyboard.down('KeyW');
  await page.waitForFunction(() => window.demoDebug.getState().gait === 'sprint');
  await page.keyboard.up('KeyW'); await page.keyboard.up('Shift');
  assert.equal((await state()).dir, 'back');
  await page.click('[data-sex="female"]');
  await page.click('[data-gait="walk"]');
  await page.click('[data-dir="right"]');
  await page.click('#next');
  const paused = await state();
  assert.equal(paused.paused,true); assert.equal(paused.frameCount,4);
  await page.evaluate(() => new Promise(resolve => setTimeout(resolve,400)));
  assert.equal((await state()).frame,paused.frame);
  await page.click('#next'); assert.equal((await state()).frame,(paused.frame+1)%4);
  await page.selectOption('#ground','light');
  await page.selectOption('#zoom','1');
  await page.screenshot({path:path.join(__dirname,'review/demo-motion-native.png')});
  await page.selectOption('#study','darts');
  await page.click('[data-dir="right"]');
  assert.equal((await state()).frameCount,0);
  await page.waitForFunction(() => document.querySelector('#notice').textContent.includes('No generated frame'));
  await page.click('[data-dir="front"]');
  assert.equal((await state()).frameCount,1);
  await page.selectOption('#ground','dark');
  await page.selectOption('#zoom','2');
  await page.screenshot({path:path.join(__dirname,'review/demo-equipment.png')});
  await page.selectOption('#study','diagonals');
  for (const dir of ['se','ne','nw','sw']) {
    await page.click(`[data-dir="${dir}"]`);
    assert((await state()).frameSource.includes(`diagonals-${dir}`));
  }
  await page.selectOption('#study','focused-walk');
  await page.click('[data-dir="right"]');
  assert.equal((await state()).frameCount,4);
  assert.equal(await page.evaluate(() => document.querySelector('#scene').getContext('2d').imageSmoothingEnabled),false);
  await page.setViewportSize({width:800,height:800});
  await page.screenshot({path:path.join(__dirname,'review/demo-compact.png')});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth),false);
  assert.deepEqual(errors,[]); assert.deepEqual(badResponses,[]);
  const result = {passed:true,frameCount:count,checks:['all sprite assets decode','keyboard movement','shift sprint selection','explicit facing mapping','sex change','pause and frame stepping','missing combinations remain empty','all four diagonal references','focused walk strip','nearest-neighbor canvas','compact layout'],pageErrors:errors,badResponses};
  fs.writeFileSync(path.join(__dirname,'review/demo-verification.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result)); await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
