const $=s=>document.querySelector(s);
const canvas=$('#scene'),ctx=canvas.getContext('2d');
const original='../../starter-slice-v02-identities/native-alpha/frames/';
const state={sex:'male',study:'motion',gait:'sprint',baseGait:'sprint',dir:'right',frame:0,paused:false,inPlace:true,zoom:2,ground:'village',x:0,y:25,elapsed:0,moving:false,processing:'tuned',showAnchors:true};
const cardinal=['front','right','back','left'],diagonal=['se','ne','nw','sw'];
const labels={front:'↓ S',right:'→ E',back:'↑ N',left:'← W',se:'↘ SE',ne:'↗ NE',nw:'↖ NW',sw:'↙ SW'};
const assets=new Map(),keys=new Set(),manifests={};let manifest,lastStrip='',lastFrame='',last=0,ready=false;
const props=[['dwelling',-180,-95],['dwelling',175,-110],['shrine',10,-100],['tree',-300,60],['tree',310,100],['tree',-95,200],['tree',230,240],['tree',320,-210],['tree',-310,-180]];
const villagers=[['field-hand',-120,55,'right'],['scribe',75,-10,'front'],['scout',-80,-50,'front'],['defender',135,105,'left'],['pack-wolf',-220,170,'right'],['well-alpha',235,190,'left']];
async function load(src){if(assets.has(src))return assets.get(src);const im=new Image();im.src=src;await im.decode();assets.set(src,im);return im;}
function currentClip(){
 if(state.study==='club')return {frames:[{src:original+`player-${state.sex}-${state.dir}.png`,width:48,height:96,anchor:[24,94]}],note:'Original four-facing idle. Movement translates an idle sprite; it is not a walk animation.'};
 const key=state.study==='motion'?`${state.sex}-${state.gait}-${state.dir}`:`${state.sex}-${state.study}-${state.dir}`;
 return manifest?.clips[key]||{frames:[],note:'This combination has no generated frames. Choose an available direction; no substitute is drawn.'};
}
function selectedFrame(){const clip=currentClip();return clip.frames[state.frame%Math.max(1,clip.frames.length)];}
function markButtons(){document.querySelectorAll('[data-sex]').forEach(b=>b.classList.toggle('active',b.dataset.sex===state.sex));document.querySelectorAll('[data-gait]').forEach(b=>b.classList.toggle('active',state.study==='motion'&&b.dataset.gait===state.gait));document.querySelectorAll('[data-dir]').forEach(b=>b.classList.toggle('active',b.dataset.dir===state.dir));$('#pause').textContent=state.paused?'Play':'Pause';}
function directions(){const dirs=state.study==='diagonals'?diagonal:cardinal;$('#directions').replaceChildren(...dirs.map(d=>{const b=document.createElement('button');b.textContent=labels[d];b.dataset.dir=d;b.onclick=()=>{state.dir=d;state.frame=0;state.elapsed=0;markButtons();};return b;}));if(!dirs.includes(state.dir))state.dir=dirs[0];markButtons();}
function changeSex(sex){state.sex=sex;state.frame=0;markButtons();}
document.querySelectorAll('[data-sex]').forEach(b=>b.onclick=()=>changeSex(b.dataset.sex));
function playGait(gait){state.study='motion';state.gait=gait;state.baseGait=gait;state.paused=false;state.inPlace=true;state.frame=0;state.elapsed=0;$('#study').value='motion';$('#in-place').checked=true;$('#fps').value=gait==='sprint'?8:6;$('#fps-label').textContent=$('#fps').value+' fps';directions();canvas.focus();}
document.querySelectorAll('[data-gait]').forEach(b=>b.onclick=()=>playGait(b.dataset.gait));
$('#study').onchange=e=>{state.study=e.target.value;state.paused=false;state.frame=0;state.elapsed=0;directions();};
$('#zoom').onchange=e=>{state.zoom=Number(e.target.value);$('#scale-label').textContent=`${state.zoom}× sprite pixels`;};
$('#processing').onchange=e=>{state.processing=e.target.value;manifest=manifests[state.processing];state.frame=0;lastStrip='';lastFrame='';};
$('#anchors').onchange=e=>{state.showAnchors=e.target.checked;};
$('#ground').onchange=e=>{state.ground=e.target.value;};
$('#in-place').onchange=e=>{state.inPlace=e.target.checked;};
$('#pause').onclick=()=>{state.paused=!state.paused;markButtons();};
function step(d){state.paused=true;const n=currentClip().frames.length;state.frame=n?(state.frame+d+n)%n:0;state.elapsed=0;markButtons();}
$('#previous').onclick=()=>step(-1);$('#next').onclick=()=>step(1);
$('#fps').oninput=e=>{$('#fps-label').textContent=`${e.target.value} fps`;};
$('#reset').onclick=()=>{state.x=0;state.y=25;canvas.focus();};
window.addEventListener('keydown',e=>{if(/INPUT|SELECT/.test(e.target.tagName))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight','Space','Digit1','Digit2'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.repeat)return;if(e.code==='Space')$('#pause').click();if(e.code==='Digit1')changeSex('male');if(e.code==='Digit2')changeSex('female');});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden)keys.clear();});
canvas.addEventListener('pointerdown',()=>canvas.focus());
new ResizeObserver(()=>{const r=canvas.getBoundingClientRect();canvas.width=Math.round(r.width);canvas.height=Math.round(r.height);ctx.imageSmoothingEnabled=false;}).observe(canvas);
// Existing prototype scenery was authored on a magenta matte. Decode that legacy
// format at runtime. Player sprites use their returned PNG alpha without keying.
function decodeScenery(im){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const p=g.getImageData(0,0,c.width,c.height);let l=c.width,r=0,t=c.height,b=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const i=(y*c.width+x)*4;if(p.data[i]>40&&p.data[i+2]>40&&p.data[i]>p.data[i+1]*1.5&&p.data[i+2]>p.data[i+1]*1.5){p.data[i+3]=0;}else if(p.data[i+3]){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y);}}g.putImageData(p,0,0);const out=document.createElement('canvas');out.width=r-l+1;out.height=b-t+1;out.getContext('2d').drawImage(c,l,t,out.width,out.height,0,0,out.width,out.height);return out;}
const scenery={};let terrain;
function buildTerrain(){terrain=document.createElement('canvas');terrain.width=1200;terrain.height=1000;const g=terrain.getContext('2d');g.fillStyle=g.createPattern(assets.get('assets/tile_grass.png'),'repeat');g.fillRect(0,0,1200,1000);g.fillStyle='#263520a8';g.fillRect(0,0,1200,1000);let seed=3431;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<90000;i++){const x=rand()*1200,y=rand()*1000,wx=x-600,wy=y-500;const path=Math.abs(wx-30*Math.sin(wy*.016))<28||Math.abs(wy+30-15*Math.cos(wx*.014))<22;const green=(wx*wx/210**2+wy*wy/150**2)<1;g.fillStyle=path?(rand()>.5?'#6b6147':'#5d543e'):green?(rand()>.5?'#5b5e3d':'#464e32'):(rand()>.5?'#414c2e':'#303e27');if(path||green||rand()<.06)g.fillRect(x|0,y|0,2+rand()*4|0,1+rand()*2|0);}}
function screen(x,y){return [Math.round(canvas.width/2+(x-state.x)*state.zoom),Math.round(canvas.height*.6+(y-state.y)*state.zoom)];}
function drawSprite(im,x,y,w,h,anchor,shadow=true){const [sx,sy]=screen(x,y),z=state.zoom;if(shadow){ctx.fillStyle='#11180f55';ctx.beginPath();ctx.ellipse(sx,sy-1,12*z,4*z,0,0,Math.PI*2);ctx.fill();}ctx.drawImage(im,sx-anchor[0]*z,sy-anchor[1]*z,w*z,h*z);}
function missing(g,x,y,w,h){g.strokeStyle='#cfac78';g.setLineDash([3,3]);g.strokeRect(x,y,w,h);g.setLineDash([]);g.fillStyle='#e5d2ae';g.font='11px system-ui';g.textAlign='center';g.fillText('NO FRAME',x+w/2,y+h/2);}
function renderDesk(){const clip=currentClip(),f=selectedFrame(),id=[state.sex,state.study,state.gait,state.dir].join('/');const signature=id+'/'+state.frame;if(signature===lastFrame)return;lastFrame=signature;const refDir=cardinal.includes(state.dir)?state.dir:(state.dir==='ne'||state.dir==='nw'?'back':'front');const ref=assets.get(original+`player-${state.sex}-${refDir}.png`);for(const [sel,im,frame]of [['#reference',ref,{width:48,height:96,anchor:[24,94]}],['#preview',f&&assets.get(f.src),f]]){const c=$(sel),g=c.getContext('2d');const maxW=Math.max(48,f?.width||48),maxH=Math.max(96,f?.height||96);c.width=maxW;c.height=maxH;c.style.width=`${maxW}px`;c.style.height=`${maxH}px`;g.clearRect(0,0,c.width,c.height);g.imageSmoothingEnabled=false;if(im&&frame)g.drawImage(im,Math.floor(maxW/2)-frame.anchor[0],maxH-2-frame.anchor[1],frame.width,frame.height);else missing(g,2,2,maxW-4,maxH-4);}$('#frame-label').textContent=f?`${labels[state.dir]} · ${state.frame+1}/${clip.frames.length} · ${f.width}×${f.height}`:'No frame';$('#quality').textContent=clip.note||'Generated animation study; inspect face, costume, gait and root stability.';if(id!==lastStrip){lastStrip=id;$('#strip').replaceChildren(...clip.frames.map((f,i)=>{const b=document.createElement('button'),im=document.createElement('img');im.src=f.src;im.style.width=f.width+'px';im.style.height=f.height+'px';im.alt=`${state.dir} frame ${i+1}`;b.append(im,document.createTextNode(`Frame ${i+1}`));b.onclick=()=>{state.frame=i;state.paused=true;markButtons();};return b;}));}$('#strip').querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===state.frame));}
function tick(now){const dt=Math.min((now-last)/1000||0,.05);last=now;if(!ready){requestAnimationFrame(tick);return;}const dx=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),dy=Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp'));state.moving=!!(dx||dy);if(state.moving){let dir;if(state.study==='diagonals')dir=dy<0?(dx<0?'nw':'ne'):(dx<0?'sw':'se');else dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'front':'back');if(state.dir!==dir){state.dir=dir;markButtons();}const sprint=keys.has('ShiftLeft')||keys.has('ShiftRight')||state.baseGait==='sprint';if(state.study==='motion'&&state.gait!==(sprint?'sprint':(state.baseGait||'sprint'))){state.gait=sprint?'sprint':(state.baseGait||'sprint');state.frame=0;state.elapsed=0;markButtons();}const len=Math.hypot(dx,dy);state.x=Math.max(-400,Math.min(400,state.x+dx/len*(sprint?105:55)*dt));state.y=Math.max(-280,Math.min(300,state.y+dy/len*(sprint?105:55)*dt));}
const clip=currentClip();if(!state.paused&&(state.inPlace||state.moving)&&clip.frames.length>1){state.elapsed+=dt;const fps=Number($('#fps').value);while(state.elapsed>=1/fps){state.elapsed-=1/fps;state.frame=(state.frame+1)%clip.frames.length;}}const f=selectedFrame();$('#dimension-status').textContent=f&& (f.width!==48||f.height!==96)?`Scale review: ${f.width}×${f.height} frame · 48×96 target not met`:'48×96 frame';$('#playback-status').textContent=`${state.paused?'PAUSED':'PLAYING'} · ${state.study==='motion'?state.gait.toUpperCase():state.study.toUpperCase()} · ${labels[state.dir]} · Frame ${state.frame+1}/${clip.frames.length}`;$('#notice').textContent=!f?'No generated frame for this combination. Use the direction buttons to inspect available frames.':(!state.moving&&state.inPlace&&state.study==='motion'?(state.paused?'Paused · use frame arrows to inspect':'Playing in place · use WASD to move through the village'):'');ctx.imageSmoothingEnabled=false;ctx.fillStyle=state.ground==='light'?'#d3ceba':state.ground==='dark'?'#252d30':'#303d26';ctx.fillRect(0,0,canvas.width,canvas.height);
if(state.ground==='village'){const [x,y]=screen(-600,-500);ctx.drawImage(terrain,x,y,1200*state.zoom,1000*state.zoom);}
const drawables=[];if(state.ground==='village')for(const [name,x,y]of props){drawables.push({y,draw:()=>{const im=scenery[name];const scale=name==='shrine'?.45:name==='tree'?.65:.8;drawSprite(im,x,y,Math.round(im.width*scale),Math.round(im.height*scale),[Math.round(im.width*scale/2),Math.round(im.height*scale)-4],false);}});}
for(const [actor,x,y,d]of villagers){drawables.push({y,draw:()=>{const im=assets.get(original+`${actor}-${d}.png`),w=actor.includes('wolf')||actor==='well-alpha'?96:48;drawSprite(im,x,y,w,96,[w/2,94]);}});}
// Companion uses the same requested clip, exposing male/female scale drift together.
const other=state.sex==='male'?'female':'male',otherKey=state.study==='motion'?`${other}-${state.gait}-${state.dir}`:`${other}-${state.study}-${state.dir}`;
const otherClip=state.study==='club'?{frames:[{src:original+`player-${other}-${state.dir}.png`,width:48,height:96,anchor:[24,94]}]}:manifest.clips[otherKey];
const of=otherClip?.frames[state.frame%otherClip.frames.length];drawables.push({y:state.y,draw:()=>{const [x,y]=screen(state.x,state.y);ctx.strokeStyle='#c7be83a0';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(x,y,15*state.zoom,5*state.zoom,0,0,Math.PI*2);ctx.stroke();if(f){drawSprite(assets.get(f.src),state.x,state.y,f.width,f.height,f.anchor);if(state.showAnchors){ctx.strokeStyle='#83e0d7';ctx.beginPath();ctx.moveTo(x,y-175*state.zoom);ctx.lineTo(x,y+10);ctx.moveTo(x-8,y);ctx.lineTo(x+8,y);ctx.stroke();}}else missing(ctx,x-24*state.zoom,y-94*state.zoom,48*state.zoom,96*state.zoom);}});
if(of)drawables.push({y:state.y+7,draw:()=>drawSprite(assets.get(of.src),state.x+60,state.y+7,of.width,of.height,of.anchor)});
drawables.sort((a,b)=>a.y-b.y).forEach(d=>d.draw());renderDesk();requestAnimationFrame(tick);}
async function init(){try{const response=await fetch('../manifest.json');if(!response.ok)throw Error('Missing frame manifest');manifests.before=await response.json();const tunedResponse=await fetch('../manifest-tuned.json');if(!tunedResponse.ok)throw Error('Missing tuned frame manifest');manifests.tuned=await tunedResponse.json();manifest=manifests.tuned;for(const clip of Object.values(manifests).flatMap(m=>Object.values(m.clips)))for(const f of clip.frames)f.src='../'+f.src;const urls=new Set();for(const clip of Object.values(manifests).flatMap(m=>Object.values(m.clips)))for(const f of clip.frames)urls.add(f.src);for(const sex of ['male','female'])for(const dir of cardinal)urls.add(original+`player-${sex}-${dir}.png`);for(const [a,,,d]of villagers)urls.add(original+`${a}-${d}.png`);for(const name of ['dwelling','tree','shrine','tile_grass'])urls.add(`assets/${name}.png`);await Promise.all([...urls].map(load));for(const n of ['dwelling','tree','shrine'])scenery[n]=decodeScenery(assets.get(`assets/${n}.png`));buildTerrain();directions();ready=true;canvas.focus();}catch(e){$('#notice').textContent=`Unable to load the demo: ${e.message}`;console.error(e);}}
window.demoDebug={getState:()=>({...state,ready,frameSource:selectedFrame()?.src,frameCount:currentClip().frames.length,loaded:assets.size}),getManifest:()=>manifest,getManifests:()=>manifests};
init();requestAnimationFrame(tick);
